### ISSUE TITLE
Cannot plot non-interactively

### ISSUE THREAD

**Issue by Lolcroc** [watermarkhu/OpenSurfaceSim#32]
### **Steps to reproduce**

```
from opensurfacesim.main import initialize, run
code, decoder = initialize((6,6), "toric", "mwpm", enabled_errors=["pauli"])
run(code, decoder, iterations=10, error_rates = {"p_bitflip": 0.1})
```

### **Issue**

```
Matplotlib is using Qt5Agg backend. Interactive plotting is disabled.
Drawing 1/1: Initial
Traceback (most recent call last):
  File "*\stuff.py", line 2, in <module>
    code, decoder = initialize((6, 6), "toric", "mwpm", enabled_errors=["pauli"], plotting=True, initial_states=(0, 0))
  File *\opensurfacesim\main.py", line 91, in initialize
    code.initialize(*enabled_errors, **kwargs)
  File "*\opensurfacesim\codes\_template\plot.py", line 35, in initialize
    self.figure.draw_figure("Initial")
  File "*\opensurfacesim\plot.py", line 649, in draw_figure
    self.display(self.figure)
AttributeError: 'Figure' object has no attribute 'display'
```

### **Suggested fix**

`load_interactive_backend(self)` should create a `self.display` for non-inline/non-interactive mpl backends (such as Qt5Agg).

**Comment by watermarkhu** [comment]
Hi!

Qt5Agg is not a non-interactive backend, but that is a plus. It seems that the code for interactive plotting using the Tkinter backend is compatible with Qt5Agg, since we used matplotlib tools instead of native Tkinter. I've setup a new [branch](https://github.com/watermarkhu/OpenSurfaceSim/tree/development-qt5agg) that targets Qt5Agg support. Please test it and report for any errors, since currently there are no tests setup for the plotting gui's. 

Best, Mark
